### ISSUE TITLE
유튜브api로 가져오는 데이터 mongoDB에 저장해보기

### ISSUE THREAD

**Issue by mochapoke** [mochapoke/kpop-master#42]
youtube v3 API는 하루, 분당 할당량이 정해져있음. 
하루 할당량을 채우지 못했어도 분당 할달량을 채우면 일정시간이 지나야 사용가능함.
그이상을 원한다면 유료결제가 필요.

어짜피 가져오는 데이터는 거의 비슷할텐데 굳이 매번 youtube api로 데이터를 가져와야 할까?
유명한 가수들이나 년도별, 이번주 목록의 youtube 데이터를 가져올때마다 어딘가에 저장해놓고 가져온다면 어떨까? api사용량이 확 줄어들지 않을까?

유저들의 브라우저의 session이나 local storage에 저장하는 것은 내 의도에 어긋남.
mongoDB에 저장해서 가져와볼까?
.... 버젼3에 적용해봐야겠음!

**Comment by mochapoke** [comment]
완료

**Comment by chohohee** [comment]
혹시 분당 할달량이 얼마나 되나요?

**Comment by suyoungDev** [comment]
> 혹시 분당 할달량이 얼마나 되나요?
음.. 거의 작년일이라 까먹었는데 대충 50 ~ 100회 정도였던걸로 기억합니다.
이제 없어졌을 수도 있어요 🤔
